Repository mbg/uow-apis, pull requests merged in 2020-10, with the labels that each got.

#23 Add Postroom API (public and own controllers)
  README.md
  src/Warwick/Postroom.hs
  src/Warwick/Postroom/API.hs
  src/Warwick/Postroom/OpeningTimes.hs
  src/Warwick/Postroom/PostItem.hs
  src/Warwick/Postroom/PostroomHub.hs
  src/Warwick/Postroom/Recipient.hs
Labels: enhancement, hacktoberfest-accepted

#24 Try short sha (untested)
  .github/workflows/haskell.yml
Labels: enhancement, hacktoberfest-accepted

#25 Add sitebuilder "sync" function to uow-util
  README.md
  app/CmdArgs.hs
  app/Sitebuilder.hs
  docs/Sitebuilder/Sync.md
  package.yaml
  src/Warwick/Sitebuilder/PageInfo.hs
  src/Warwick/Sitebuilder/PageOptions.hs
Labels: enhancement, hacktoberfest-accepted

#26 `path` -> `page` in `sync` docs
  docs/Sitebuilder/Sync.md
Labels: bug

#28 Add some logging to sitebuilder sync
  app/Sitebuilder.hs
Labels: enhancement
